var searchData=
[
  ['executenonqueryembeddedresource',['ExecuteNonQueryEmbeddedResource',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a1771dc6ce56e06896c5166aedb9865f6',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#af79b3af91a03769be959db25ab7da2c4',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=true)']]],
  ['executenonqueryembeddedresourceforobject_3c_20t_20_3e',['ExecuteNonQueryEmbeddedResourceForObject&lt; T &gt;',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ad0536fa39725f5d74e852d8557e809a3',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObject&lt; T &gt;(this IDbConnection connection, string embeddedResource, T obj, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a240702d72ab523c5e82b8609ede4c68c',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObject&lt; T &gt;(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, T obj, bool validateParameters=true)']]],
  ['executenonqueryembeddedresourceforobjects_3c_20t_20_3e',['ExecuteNonQueryEmbeddedResourceForObjects&lt; T &gt;',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a651d37d4cc8638362c2aa61f404ca6e4',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObjects&lt; T &gt;(this IDbConnection connection, string embeddedResource, IEnumerable&lt; T &gt; objects, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a970d3ce30d0c0b0eaf25b96b9ebda432',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObjects&lt; T &gt;(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, IEnumerable&lt; T &gt; objects, bool validateParameters=true)']]],
  ['executenonquerystring',['ExecuteNonQueryString',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ab5556c5cbfe794c4669a4dd9ba80475b',1,'BlueCloud::Extensions::Data::IDbConnectionExtensions']]],
  ['executenonquerystringforobject_3c_20t_20_3e',['ExecuteNonQueryStringForObject&lt; T &gt;',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ab213db156b4cc0b81d0bf4a00b777765',1,'BlueCloud::Extensions::Data::IDbConnectionExtensions']]],
  ['executequeryembeddedresource',['ExecuteQueryEmbeddedResource',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#adf6d4a060eb0a30d358d31aa66555f1c',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDbCommand &gt; commandCallback, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a29824247ed676b9d944fc63bfc48875f',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#af955729e166df12ee7c5856798c7e047',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDbCommand &gt; commandCallback, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a7b2fc0f0635efd4c13fc3201abc8757f',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=true)']]],
  ['executequeryscalar',['ExecuteQueryScalar',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ac7cb1d2c56a995698c583329b4fe8cef',1,'BlueCloud::Extensions::Data::IDbConnectionExtensions']]],
  ['executequerystring',['ExecuteQueryString',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a75afa37354f81fa82c594e06d5bda02c',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryString(this IDbConnection connection, string sqlString, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ad6bda36c6d7ca4641d58888ffdd3fb7a',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryString(this IDbConnection connection, string sqlString, Action&lt; IDbCommand &gt; commandCallback, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=true)']]],
  ['executescalarembeddedresource',['ExecuteScalarEmbeddedResource',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a1280135ed5932e67c193fc5367b520a9',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteScalarEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=true)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ab1c2668a66de9eb0c17b411cc246c9a1',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteScalarEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=true)']]]
];
