var searchData=
[
  ['executenonqueryembeddedresource',['ExecuteNonQueryEmbeddedResource',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#af48b91dbba9d032dbd364a0ce48a7238',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a3dcbcb9d09dd691c17bc9652fa2894b1',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=false)']]],
  ['executenonqueryembeddedresourceforobject_3c_20t_20_3e',['ExecuteNonQueryEmbeddedResourceForObject&lt; T &gt;',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#af558e620660d15904b4eec510bd47af5',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObject&lt; T &gt;(this IDbConnection connection, string embeddedResource, T obj, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#abc6cbdf1b238168f13a6b2a88e309743',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObject&lt; T &gt;(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, T obj, bool validateParameters=false)']]],
  ['executenonqueryembeddedresourceforobjects_3c_20t_20_3e',['ExecuteNonQueryEmbeddedResourceForObjects&lt; T &gt;',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a03e05fb2dd4ab39d85a77addd01b12e1',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObjects&lt; T &gt;(this IDbConnection connection, string embeddedResource, IEnumerable&lt; T &gt; objects, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ace41ced3582ae6d75803703d3213c099',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteNonQueryEmbeddedResourceForObjects&lt; T &gt;(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, IEnumerable&lt; T &gt; objects, bool validateParameters=false)']]],
  ['executenonquerystring',['ExecuteNonQueryString',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#adfac9ac363eeb9545af9b3a662f438df',1,'BlueCloud::Extensions::Data::IDbConnectionExtensions']]],
  ['executenonquerystringforobject_3c_20t_20_3e',['ExecuteNonQueryStringForObject&lt; T &gt;',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ab62a6fdee017e2623bed5e2f1e8ebc1f',1,'BlueCloud::Extensions::Data::IDbConnectionExtensions']]],
  ['executenonquerystringforobjects_3c_20t_20_3e',['ExecuteNonQueryStringForObjects&lt; T &gt;',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a3b70dc8befcb44864a49795cd865c50d',1,'BlueCloud::Extensions::Data::IDbConnectionExtensions']]],
  ['executequeryembeddedresource',['ExecuteQueryEmbeddedResource',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a430c474cab2d89d20604579a66052020',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDbCommand &gt; commandCallback, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a51679e971136235758d02f0bcdeb1822',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a027aaac95ad6cea7e42317bd2b3ec9ac',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDbCommand &gt; commandCallback, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a8d29f18027a4b5f1bba7d2dbf5a2ea6c',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=false)']]],
  ['executequeryscalar',['ExecuteQueryScalar',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ae18988406fddb5b1d39db4d364f258b5',1,'BlueCloud::Extensions::Data::IDbConnectionExtensions']]],
  ['executequerystring',['ExecuteQueryString',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a3b45608e2c25aa1275229f99be2d929b',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryString(this IDbConnection connection, string sqlString, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#a323ca90a66dc4e4319b94718ee6cf35c',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteQueryString(this IDbConnection connection, string sqlString, Action&lt; IDbCommand &gt; commandCallback, Action&lt; IDataReader &gt; readerCallback, bool validateParameters=false)']]],
  ['executescalarembeddedresource',['ExecuteScalarEmbeddedResource',['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#adc070329fd92b0fa1e2c928671147e0f',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteScalarEmbeddedResource(this IDbConnection connection, string embeddedResource, System.Reflection.Assembly assembly, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=false)'],['../class_blue_cloud_1_1_extensions_1_1_data_1_1_i_db_connection_extensions.html#ad7fb52092d3f2bd4fa11d0da0bffd576',1,'BlueCloud.Extensions.Data.IDbConnectionExtensions.ExecuteScalarEmbeddedResource(this IDbConnection connection, string embeddedResource, Action&lt; IDbCommand &gt; commandCallback=null, bool validateParameters=false)']]]
];
